name: MyRunner with Flask-Docker

on:
  push:
    branches:
      - main

jobs:
  docker-buid:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
      
        run: |
          docker build -t dockerimage .
