name: MyRunner with Flask-Docker

on:
  push:
    branches:
      - main

jobs:
  docker-buid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login into DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
      
        run: |
          export DOCKER_BUILDKIT=0
          docker build -t vempadasivakumarreddy/githubactions .

      - name: Push DOkcer Image
        run: docker push vempadasivakumarreddy/githubactions:latest

      - name: Logout from DOcker Hub
        run: docker logout

      - name: Dummy Test Output
        run: |
          mkdir -p test-results
          echo "Tests passed successfully" > test-results/result.txt

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: test-results
         
