name: MyRunner with Flask-Docker

on:
  push:
    branches:
      - main

jobs:
  docker-buid:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login into DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
      
        run: |
          export DOCKER_BUILDKIT=0
          docker build -t vempadasivakumarreddy/githubactions .

      - name: Push DOkcer Image
        run: docker push vempadasivakumarreddy/githubactions:latest

      - name: Logout from DOcker Hub
        run: docker logout
         
